### ISSUE TITLE
oss-app: Unable to init server: Could not connect: Connection refused

### ISSUE THREAD

**Issue by valeriocos** [crossminer/scava#131]
It seems that the oss-app is not able to start. @ambpro do you experience the same problem?

```
oss-app_1         | Starting Admin bundle
auth-server_1     | 
auth-server_1     |   .   ____          _            __ _ _
auth-server_1     |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
auth-server_1     | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
auth-server_1     |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
auth-server_1     |   '  |____| .__|_| |_|_| |_\__, | / / / /
auth-server_1     |  =========|_|==============|___/=/_/_/_/
auth-server_1     |  :: Spring Boot ::        (v1.5.2.RELEASE)
auth-server_1     | 
auth-server_1     | 2019-03-06 10:50:22.746  INFO 1 --- [           main] o.e.s.a.AuthServiceApplication           : No active profile set, falling back to default profiles: default
auth-server_1     | 2019-03-06 10:50:22.800  INFO 1 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@6737fd8f: startup date [Wed Mar 06 10:50:22 GMT 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@78e03bb5
oss-app_1         | INFO  [OssmeterApplication] (10:50:22): Application initialising.
oss-app_1         | Mar 06, 2019 10:50:23 AM com.mongodb.DBTCPConnector initDirectConnection
oss-app_1         | WARNING: Exception executing isMaster command on /127.0.0.1:27017
oss-app_1         | java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused (Connection refused)
oss-app_1         | 	at com.mongodb.DBPort._open(DBPort.java:214)
oss-app_1         | 	at com.mongodb.DBPort.go(DBPort.java:107)
oss-app_1         | 	at com.mongodb.DBPort.go(DBPort.java:88)
oss-app_1         | 	at com.mongodb.DBPort.findOne(DBPort.java:143)
oss-app_1         | 	at com.mongodb.DBPort.runCommand(DBPort.java:148)
oss-app_1         | 	at com.mongodb.DBTCPConnector.initDirectConnection(DBTCPConnector.java:544)
oss-app_1         | 	at com.mongodb.DBTCPConnector.isMongosConnection(DBTCPConnector.java:369)
oss-app_1         | 	at com.mongodb.Mongo.isMongosConnection(Mongo.java:607)
oss-app_1         | 	at com.mongodb.DBCollection.findOne(DBCollection.java:706)
oss-app_1         | 	at com.mongodb.DBCollection.findOne(DBCollection.java:652)
oss-app_1         | 	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:343)
oss-app_1         | 	at com.mongodb.DBCollection.createIndex(DBCollection.java:467)
oss-app_1         | 	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:543)
oss-app_1         | 	at com.googlecode.pongo.runtime.PongoCollection.createIndex(PongoCollection.java:27)
oss-app_1         | 	at org.eclipse.scava.repository.model.ProjectCollection.<init>(ProjectCollection.java:20)
oss-app_1         | 	at org.eclipse.scava.repository.model.ProjectRepository.setDb(ProjectRepository.java:95)
oss-app_1         | 	at org.eclipse.scava.repository.model.ProjectRepository.<init>(ProjectRepository.java:20)
oss-app_1         | 	at org.eclipse.scava.platform.ProjectRepositoryManager.init(ProjectRepositoryManager.java:34)
oss-app_1         | 	at org.eclipse.scava.platform.ProjectRepositoryManager.<init>(ProjectRepositoryManager.java:29)
oss-app_1         | 	at org.eclipse.scava.platform.Platform.<init>(Platform.java:54)
oss-app_1         | 	at org.eclipse.scava.platform.osgi.OssmeterApplication.start(OssmeterApplication.java:64)
oss-app_1         | 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
oss-app_1         | 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
oss-app_1         | 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
oss-app_1         | 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
oss-app_1         | 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
oss-app_1         | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
oss-app_1         | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
oss-app_1         | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
oss-app_1         | 	at java.lang.reflect.Method.invoke(Method.java:498)
oss-app_1         | 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
oss-app_1         | 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
oss-app_1         | 	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
oss-app_1         | 	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
oss-app_1         | 
oss-app_1         | Mar 06, 2019 10:50:23 AM com.mongodb.DBTCPConnector initDirectConnection
oss-app_1         | WARNING: Exception executing isMaster command on /127.0.0.1:27017
oss-app_1         | java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused (Connection refused)
oss-app_1         | 	at com.mongodb.DBPort._open(DBPort.java:214)
oss-app_1         | 	at com.mongodb.DBPort.go(DBPort.java:107)
oss-app_1         | 	at com.mongodb.DBPort.go(DBPort.java:88)
oss-app_1         | 	at com.mongodb.DBPort.findOne(DBPort.java:143)
oss-app_1         | 	at com.mongodb.DBPort.runCommand(DBPort.java:148)
oss-app_1         | 	at com.mongodb.DBTCPConnector.initDirectConnection(DBTCPConnector.java:544)
oss-app_1         | 	at com.mongodb.DBTCPConnector.checkMaster(DBTCPConnector.java:523)
oss-app_1         | 	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:274)
oss-app_1         | 	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:256)
oss-app_1         | 	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:289)
oss-app_1         | 	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:274)
oss-app_1         | 	at com.mongodb.DBCollection.findOne(DBCollection.java:710)
oss-app_1         | 	at com.mongodb.DBCollection.findOne(DBCollection.java:652)
oss-app_1         | 	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:343)
oss-app_1         | 	at com.mongodb.DBCollection.createIndex(DBCollection.java:467)
oss-app_1         | 	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:543)
oss-app_1         | 	at com.googlecode.pongo.runtime.PongoCollection.createIndex(PongoCollection.java:27)
oss-app_1         | 	at org.eclipse.scava.repository.model.ProjectCollection.<init>(ProjectCollection.java:20)
oss-app_1         | 	at org.eclipse.scava.repository.model.ProjectRepository.setDb(ProjectRepository.java:95)
oss-app_1         | 	at org.eclipse.scava.repository.model.ProjectRepository.<init>(ProjectRepository.java:20)
oss-app_1         | 	at org.eclipse.scava.platform.ProjectRepositoryManager.init(ProjectRepositoryManager.java:34)
oss-app_1         | 	at org.eclipse.scava.platform.ProjectRepositoryManager.<init>(ProjectRepositoryManager.java:29)
oss-app_1         | 	at org.eclipse.scava.platform.Platform.<init>(Platform.java:54)
oss-app_1         | 	at org.eclipse.scava.platform.osgi.OssmeterApplication.start(OssmeterApplication.java:64)
oss-app_1         | 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
oss-app_1         | 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
oss-app_1         | 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
oss-app_1         | 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
oss-app_1         | 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
oss-app_1         | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
oss-app_1         | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
oss-app_1         | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
oss-app_1         | 	at java.lang.reflect.Method.invoke(Method.java:498)
oss-app_1         | 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
oss-app_1         | 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
oss-app_1         | 	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
oss-app_1         | 	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
oss-app_1         | 
oss-app_1         | Mar 06, 2019 10:50:23 AM com.mongodb.DBPortPool gotError
oss-app_1         | WARNING: emptying DBPortPool to /127.0.0.1:27017 b/c of error
oss-app_1         | java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused (Connection refused)
oss-app_1         | 	at com.mongodb.DBPort._open(DBPort.java:214)
oss-app_1         | 	at com.mongodb.DBPort.go(DBPort.java:107)
oss-app_1         | 	at com.mongodb.DBPort.call(DBPort.java:74)
oss-app_1         | 	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:283)
oss-app_1         | 	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:256)
oss-app_1         | 	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:289)
oss-app_1         | 	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:274)
oss-app_1         | 	at com.mongodb.DBCollection.findOne(DBCollection.java:710)
oss-app_1         | 	at com.mongodb.DBCollection.findOne(DBCollection.java:652)
oss-app_1         | 	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:343)
oss-app_1         | 	at com.mongodb.DBCollection.createIndex(DBCollection.java:467)
oss-app_1         | 	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:543)
oss-app_1         | 	at com.googlecode.pongo.runtime.PongoCollection.createIndex(PongoCollection.java:27)
oss-app_1         | 	at org.eclipse.scava.repository.model.ProjectCollection.<init>(ProjectCollection.java:20)
oss-app_1         | 	at org.eclipse.scava.repository.model.ProjectRepository.setDb(ProjectRepository.java:95)
oss-app_1         | 	at org.eclipse.scava.repository.model.ProjectRepository.<init>(ProjectRepository.java:20)
oss-app_1         | 	at org.eclipse.scava.platform.ProjectRepositoryManager.init(ProjectRepositoryManager.java:34)
oss-app_1         | 	at org.eclipse.scava.platform.ProjectRepositoryManager.<init>(ProjectRepositoryManager.java:29)
oss-app_1         | 	at org.eclipse.scava.platform.Platform.<init>(Platform.java:54)
oss-app_1         | 	at org.eclipse.scava.platform.osgi.OssmeterApplication.start(OssmeterApplication.java:64)
oss-app_1         | 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
oss-app_1         | 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
oss-app_1         | 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
oss-app_1         | 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
oss-app_1         | 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
oss-app_1         | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
oss-app_1         | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
oss-app_1         | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
oss-app_1         | 	at java.lang.reflect.Method.invoke(Method.java:498)
oss-app_1         | 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
oss-app_1         | 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
oss-app_1         | 	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
oss-app_1         | 	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
oss-app_1         | 
oss-app_1         | Unable to init server: Could not connect: Connection refused
oss-app_1         | Eclipse:
oss-app_1         | GTK+ Version Check
oss-app_1         | Eclipse:
oss-app_1         | An error has occurred. See the log file
oss-app_1         | /ossmeter/configuration/1551869416906.log.
scava-deployment_oss-app_1 exited with code 13
```

**Comment by valeriocos** [comment]
Fixed with: https://github.com/crossminer/scava-deployment/commit/285dc1f082ce58529e7767080fff53b315b5f93e
