### ISSUE TITLE
Jenkins fails to build commits

### ISSUE THREAD

**Issue by valeriocos** [crossminer/scava#140]
I've recently submitted a PR (https://github.com/crossminer/scava/pull/136), which I tested locally and seems to work. When checking the Jenkins log (below a part of the stacktrace) I see:
```
java.lang.ClassNotFoundException: org.eclipse.jgit.lib.Repository cannot be found by org.eclipse.scava.platform.vcs.git_0.0.1.201903080931
```
I don't know if the problem is related to how Jenkins was deployed or some other errors in the platform.

```
INFO  [ProjectDelta (pongotest,20130131)] (10:36:35): Creating Delta

org.eclipse.core.runtime.CoreException: Plug-in "org.eclipse.scava.platform.vcs.git" was unable to instantiate class "org.eclipse.scava.platform.vcs.git.GitManager".
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:188)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.eclipse.scava.platform.delta.vcs.ExtensionPointVcsManager.getVcsManagers(ExtensionPointVcsManager.java:35)
	at org.eclipse.scava.platform.delta.vcs.PlatformVcsManager.getVcsManager(PlatformVcsManager.java:107)
	at org.eclipse.scava.platform.delta.vcs.PlatformVcsManager.getRevisionsForDate(PlatformVcsManager.java:66)
	at org.eclipse.scava.platform.delta.vcs.VcsProjectDelta.<init>(VcsProjectDelta.java:25)
	at org.eclipse.scava.platform.delta.ProjectDelta.create(ProjectDelta.java:61)
	at org.eclipse.scava.platform.osgi.analysis.ProjectAnalyser.executeAnalyse(ProjectAnalyser.java:102)
	at org.eclipse.scava.platform.tests.RunMetricsTest.testAnalyzePongo(RunMetricsTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:156)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:82)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:95)
	at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.run(HeadlessTestApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jgit/lib/Repository
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:184)
	... 61 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.jgit.lib.Repository cannot be found by org.eclipse.scava.platform.vcs.git_0.0.1.201903080931
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 66 more
```

**Comment by borisbaldassari** [comment]
I'm not sure it comes from the host itself.. Adrian @creat89 has the same problem (probably on a different part of the code). 
I can build it on my own machine btw.. I'll investigate and keep you posted.

**Comment by borisbaldassari** [comment]
It seems it started failing from build 106, which is associated to Juri's commit 3e155deedc78063fab4ebd41f54c8b0d0e9cc298 . @md2manoppello @davidediruscio could you please check what happened? the issue seems to come from there..

**Comment by davidediruscio** [comment]
@valeriocos could you please inform us about the repository you were trying to import when the error occurred? This can help to identify the error.

**Comment by davidediruscio** [comment]
Ok forget about my previou request...looking at http://ci5.castalia.camp:8080/blue/organizations/jenkins/scava-metric-platform/detail/PR-136/2/pipeline

**Comment by davidediruscio** [comment]
It seems the issue is not related to the Eclipse importer. 

We have problems during the creation of deltas. In particular, for both testAnalyzePongo and testAnalyzeVallang in the test file 

https://github.com/crossminer/scava/blob/dev/metric-platform/tests/org.eclipse.scava.platform.tests/src/org/eclipse/scava/platform/tests/RunMetricsTest.java 

there is a common aspect. The errors are raised when creating deltas from the very first dates of the vallang and pongo projects. 

Are we missing something? @ambpro

**Comment by tdegueul** [comment]
Build is back to normal: http://ci5.castalia.camp:8080/view/Dev/job/scava-metric-platform/job/dev/.

Thanks @ambpro.

**Comment by davidediruscio** [comment]
@tdegueul can we close then?
