### ISSUE TITLE
numberUniqueMavenDependencies exception

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#149]
I've been facing this exception : 
```
oss-app_1         | INFO  [MetricListExecutor (spoon, 20190106)] (14:11:16): Starting Metric Execution (numberUniqueMavenDependencies).
oss-app_1         | Runtime error in model extractor
oss-app_1         | org.rascalmpl.interpreter.control_exceptions.Throw: |std:///IO.rsc|:588,0: PathNotFound(|file:///root/scava/spoon/workingCopies/https_3a__2f__2f_github_2e_com_2f_INRIA_2f_spoon_2e_git/src/test/resources/spoon/test/noclasspath/exceptions/Bar.java|)
oss-app_1         |     at org.rascalmpl.interpreter.control_exceptions.ControlException.reallyFillInStackTrace(ControlException.java:42)
oss-app_1         |     at org.rascalmpl.interpreter.control_exceptions.Throw.fillInStackTrace(Throw.java:138)
oss-app_1         |     at java.lang.Throwable.<init>(Throwable.java:265)
oss-app_1         |     at java.lang.Exception.<init>(Exception.java:66)
oss-app_1         |     at java.lang.RuntimeException.<init>(RuntimeException.java:62)
oss-app_1         |     at org.rascalmpl.interpreter.control_exceptions.ControlException.<init>(ControlException.java:25)
oss-app_1         |     at org.rascalmpl.interpreter.control_exceptions.Throw.<init>(Throw.java:73)
oss-app_1         |     at org.rascalmpl.interpreter.control_exceptions.Throw.<init>(Throw.java:93)
oss-app_1         |     at org.rascalmpl.interpreter.utils.RuntimeExceptionFactory.pathNotFound(RuntimeExceptionFactory.java:250)
oss-app_1         |     at org.rascalmpl.library.Prelude.readFileLines(Prelude.java:1327)
oss-app_1         |     at sun.reflect.GeneratedMethodAccessor134.invoke(Unknown Source)
oss-app_1         |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
oss-app_1         |     at java.lang.reflect.Method.invoke(Method.java:498)
oss-app_1         |     at org.rascalmpl.interpreter.result.JavaMethod.invoke(JavaMethod.java:230)
oss-app_1         |     at org.rascalmpl.interpreter.result.JavaMethod.call(JavaMethod.java:162)
oss-app_1         |     at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:531)
oss-app_1         |     at org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:493)
oss-app_1         |     at org.rascalmpl.semantics.dynamic.Expression$Tuple.interpret(Expression.java:2744)
oss-app_1         |     at org.rascalmpl.semantics.dynamic.SetComprehensionWriter.append(SetComprehensionWriter.java:36)
oss-app_1         |     at org.rascalmpl.semantics.dynamic.Comprehension.evalComprehension(Comprehension.java:95)
oss-app_1         |     at org.rascalmpl.semantics.dynamic.Comprehension$Set.interpret(Comprehension.java:71)
oss-app_1         |     at org.rascalmpl.semantics.dynamic.Expression$Comprehension.interpret(Expression.java:679)
oss-app_1         |     at org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:365)
oss-app_1         |     at org.rascalmpl.semantics.dynamic.Statement$Return.interpret(Statement.java:783)
oss-app_1         |     at org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:383)
oss-app_1         |     at org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:322)
oss-app_1         |     at org.rascalmpl.interpreter.result.AbstractFunction.call(AbstractFunction.java:206)
oss-app_1         |     at org.eclipse.scava.metricprovider.rascal.RascalManager$Extractor.call(RascalManager.java:105)
oss-app_1         |     at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.callExtractors(RascalMetricProvider.java:498)
oss-app_1         |     at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.computeAsts(RascalMetricProvider.java:412)
oss-app_1         |     at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.compute(RascalMetricProvider.java:265)
oss-app_1         |     at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:211)
oss-app_1         |     at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:1)
oss-app_1         |     at org.eclipse.scava.platform.osgi.analysis.MetricListExecutor.run(MetricListExecutor.java:103)
oss-app_1         |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
oss-app_1         |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
oss-app_1         |     at java.lang.Thread.run(Thread.java:748)
oss-app_1         | Rascal stack trace:
oss-app_1         |     at *** somewhere ***(|std:///IO.rsc|(14555,756,<588,0>,<608,24>))
oss-app_1         |     at readFileLines(|bundleresource://141.fwk702500163/src/Generic.rsc|(1549,4,<50,43>,<50,47>))
oss-app_1         |     at ******scava******(|main://******scava******|)
oss-app_1         |
oss-app_1         | ERROR [RascalMetricProvider (Language independent physical lines of code)] (14:11:16): ignoring all models for extractor genericAST
```
Looks like @tdegueul knows what it is about.

**Comment by tdegueul** [comment]
I hope this one was resolved by the last commits related to Delta creation. Please re-open otherwise!
