### ISSUE TITLE
com.mongodb.MongoException: Invalid ns - Exception thrown during metric provider execution (fileReadabilityQ)

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#153]
I'm facing the following exception, below is about `fileReadabilityQ` but it is thrown with `errorProneFactoid` , `ratioUnversionedOSGiImportedPackages`, `NOC_Java_Q`, `NOA_Java_Q`, `commitActivity` and more

```
INFO  [MetricListExecutor (XWikiwJIRA, 20190311)] (08:46:59): Started Metric Executed (numberUniqueMavenDependencies).
INFO  [AnalysisSchedulingService] (08:46:59): Ending MetricExecution 'trans.rascal.dependency.maven.numberUniqueMavenDependencies'
INFO  [RascalMetricProvider (All optional Maven dependencies)] (08:46:59): Calling trans.rascal.dependency.maven.allOptionalMavenDependencies
ERROR [MetricListExecutor (XWikiwJIRA, 20190311)] (08:46:59): Exception thrown during metric provider execution (fileReadabilityQ).
com.mongodb.MongoException: Invalid ns [XWiki w/JIRA.system.indexes]
	at com.mongodb.MongoException.parse(MongoException.java:82)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:293)
	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:274)
	at com.mongodb.DBCollection.findOne(DBCollection.java:710)
	at com.mongodb.DBCollection.findOne(DBCollection.java:652)
	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:343)
	at com.mongodb.DBCollection.createIndex(DBCollection.java:467)
	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:543)
	at com.googlecode.pongo.runtime.PongoCollection.createIndex(PongoCollection.java:27)
	at org.eclipse.scava.metricprovider.rascal.trans.model.MeasurementCollection.<init>(MeasurementCollection.java:24)
	at org.eclipse.scava.metricprovider.rascal.trans.model.RascalMetrics.setDb(RascalMetrics.java:39)
	at org.eclipse.scava.metricprovider.rascal.trans.model.RascalMetrics.<init>(RascalMetrics.java:22)
	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.getMetricResult(RascalMetricProvider.java:380)
	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.compute(RascalMetricProvider.java:283)
	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:211)
	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:1)
	at org.eclipse.scava.platform.osgi.analysis.MetricListExecutor.run(MetricListExecutor.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
INFO  [AnalysisSchedulingService] (08:46:59): Ending MetricExecution 'trans.rascal.readability.fileReadabilityQuartiles'
INFO  [AnalysisSchedulingService] (08:46:59): Ending MetricExecution 'trans.rascal.dependency.maven.isUsingTycho' is done.
INFO  [MetricListExecutor (XWikiwJIRA, 20190311)] (08:46:59): Ending execution AnalysisTask 'XWikiwJIRA:all' with MetricExecution 'trans.rascal.dependency.maven.isUsingTycho' done in 1840 ms
```

**Comment by mhow2** [comment]
This is issue is very old. Will close for now.
