### ISSUE TITLE
metric-platform crash when importing a github project and token is empty

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#154]
I just import a project within the admin UI:
![2019-03-27_12-25](https://user-images.githubusercontent.com/9987241/55072514-9f039880-508b-11e9-9461-bdc4c6177259.png)

At the time I press the "save" button, the oss-app container exits with the following error:
```
oss-app_1         | {"url":"https://github.com/jrwilliams/gif-hook"}
oss-app_1         | front stripped: github.com/jrwilliams/gif-hook
oss-app_1         | org.eclipse.scava.repository.model.github.GitHubBugTrackerException: Error: token is empty.
oss-app_1         |     at org.eclipse.scava.repository.model.github.GitHubBugTracker.validateEntry(GitHubBugTracker.java:81)
oss-app_1         |     at org.eclipse.scava.repository.model.github.GitHubBugTracker.setToken(GitHubBugTracker.java:173)
oss-app_1         |     at org.eclipse.scava.repository.model.github.GitHubBugTracker.setProject(GitHubBugTracker.java:54)
oss-app_1         |     at org.eclipse.scava.repository.model.github.importer.GitHubImporter.importProject(GitHubImporter.java
:380)
oss-app_1         |     at org.eclipse.scava.platform.client.api.ProjectImporter.importProject(ProjectImporter.java:77)
oss-app_1         |     at org.eclipse.scava.platform.client.api.ProjectImportResource.importProject(ProjectImportResource.jav
a:61)
oss-app_1         |     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
oss-app_1         |     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
oss-app_1         |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
oss-app_1         |     at java.lang.reflect.Method.invoke(Method.java:498)
oss-app_1         |     at org.restlet.resource.ServerResource.doHandle(ServerResource.java:521)
oss-app_1         |     at org.restlet.resource.ServerResource.post(ServerResource.java:1376)
oss-app_1         |     at org.restlet.resource.ServerResource.doHandle(ServerResource.java:621)
oss-app_1         |     at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:679)
oss-app_1         |     at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:357)
oss-app_1         |     at org.restlet.resource.ServerResource.handle(ServerResource.java:1044)
oss-app_1         |     at org.restlet.resource.Finder.handle(Finder.java:236)
oss-app_1         |     at org.restlet.routing.Filter.doHandle(Filter.java:150)
oss-app_1         |     at org.restlet.routing.Filter.handle(Filter.java:197)
oss-app_1         |     at org.restlet.routing.Router.doHandle(Router.java:422)
oss-app_1         |     at org.restlet.routing.Router.handle(Router.java:639)
oss-app_1         |     at org.restlet.routing.Filter.doHandle(Filter.java:150)
oss-app_1         |     at org.restlet.routing.Filter.handle(Filter.java:197)
oss-app_1         |     at org.restlet.routing.Filter.doHandle(Filter.java:150)
oss-app_1         |     at org.restlet.routing.Filter.handle(Filter.java:197)
oss-app_1         |     at org.restlet.routing.Filter.doHandle(Filter.java:150)
oss-app_1         |     at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
oss-app_1         |     at org.restlet.routing.Filter.handle(Filter.java:197)
oss-app_1         |     at org.restlet.routing.Filter.doHandle(Filter.java:150)
oss-app_1         |     at org.restlet.routing.Filter.handle(Filter.java:197)
oss-app_1         |     at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
oss-app_1         |     at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:75)
oss-app_1         |     at org.restlet.Application.handle(Application.java:385)
oss-app_1         |     at org.restlet.routing.Filter.doHandle(Filter.java:150)
oss-app_1         |     at org.restlet.routing.Filter.handle(Filter.java:197)
oss-app_1         |     at org.restlet.routing.Router.doHandle(Router.java:422)
oss-app_1         |     at org.restlet.routing.Router.handle(Router.java:639)
oss-app_1         |     at org.restlet.routing.Filter.doHandle(Filter.java:150)
oss-app_1         |     at org.restlet.routing.Filter.handle(Filter.java:197)
oss-app_1         |     at org.restlet.routing.Router.doHandle(Router.java:422)
oss-app_1         |     at org.restlet.routing.Router.handle(Router.java:639)
oss-app_1         |     at org.restlet.routing.Filter.doHandle(Filter.java:150)
oss-app_1         |     at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
oss-app_1         |     at org.restlet.routing.Filter.handle(Filter.java:197)
oss-app_1         |     at org.restlet.routing.Filter.doHandle(Filter.java:150)
oss-app_1         |     at org.restlet.routing.Filter.handle(Filter.java:197)
oss-app_1         |     at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
oss-app_1         |     at org.restlet.Component.handle(Component.java:408)
oss-app_1         |     at org.restlet.Server.handle(Server.java:507)
oss-app_1         |     at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)
oss-app_1         |     at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)
oss-app_1         |     at org.restlet.ext.jetty.JettyServerHelper$WrappedServer.handle(JettyServerHelper.java:273)
oss-app_1         |     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
oss-app_1         |     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
oss-app_1         |     at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
oss-app_1         |     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
oss-app_1         |     at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
oss-app_1         |     at java.lang.Thread.run(Thread.java:748)
oss-app_1         | Unable to init server: Could not connect: Connection refused
oss-app_1         | Eclipse:
oss-app_1         | GTK+ Version Check
oss-app_1         | Eclipse:
oss-app_1         | JVM terminated. Exit code=1
oss-app_1         | /usr/bin/java
oss-app_1         | -Xmx8g
oss-app_1         | -jar /ossmeter//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
oss-app_1         | -os linux
oss-app_1         | -ws gtk
oss-app_1         | -arch x86_64
oss-app_1         | -showsplash
oss-app_1         | -launcher /ossmeter/eclipse
oss-app_1         | -name Eclipse
oss-app_1         | --launcher.library /ossmeter//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.300.v20150602-1417/eclipse_1612.so
oss-app_1         | -startup /ossmeter//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
oss-app_1         | --launcher.overrideVmargs
oss-app_1         | -exitdata 0
oss-app_1         | -master
oss-app_1         | -apiServer
oss-app_1         | -worker w1
oss-app_1         | -worker w2
oss-app_1         | -config prop.properties
oss-app_1         | -vm /usr/bin/java
oss-app_1         | -vmargs
oss-app_1         | -Xmx8g
oss-app_1         | -jar /ossmeter//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
```

**Comment by creat89** [comment]
@mhow2 I have removed the lines that made Scava to finish abruptly on commit https://github.com/crossminer/scava/commit/44ce75d387bbcf6325d18a93d51bfd08b9f6b50c. However, despite that, there is a bug in the GitHub importer, that should have prevented this issue.

@md2manoppello, in theory in GitHub importer (line 348: `if (authString != null)`) you check if there is a defined token. Then, in line 379 I do the same, for setting differently GitHub Reader, one using a token and one using not authentification. Do you have an idea why the code did not prevent this issue?

**Comment by mhow2** [comment]
Now, I'm having the following:

```
oss-slave_1       | No authentification data has ben set, using public access
oss-slave_1       | INFO : GitHub Session Created.
oss-slave_1       | 11:01:18.270 ERROR [172] AbstractInterceptor$1 - UNKNOWN ERROR CODE: 404
oss-slave_1       | Exception in thread "pool-7-thread-1" java.lang.UnsupportedOperationException: Do not know how to handle this type of error code: 404
oss-slave_1       |     at org.eclipse.scava.crossflow.restmule.core.interceptor.AbstractInterceptor$1.intercept(AbstractInterceptor.java:173)
oss-slave_1       |     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
oss-slave_1       |     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
oss-slave_1       |     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
oss-slave_1       |     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
oss-slave_1       |     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
oss-slave_1       |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
oss-slave_1       |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
oss-slave_1       |     at java.lang.Thread.run(Thread.java:748)
```

**Comment by creat89** [comment]
Is it a public repository?

**Comment by mhow2** [comment]
> Is it a public repository?

Good question : the answer is yes. As SCAVA is not able to crawl non public repo, as far as I know.

**Comment by creat89** [comment]
I couldn't replicate the issue, with and without token, and using directly the bug tracker reader or using the importer. The worst thing is that RESTMULE client do not tell us much more than Error 404, which could only mean that the repository wasn't found or was private.

>  SCAVA is not able to crawl non public repo, as far as I know.

The bug tracker reader is able to read private repositories if the token provided has been allowed to read that repository. I don't know if the importer supports this or other readers, such as those based on VCS support this feature.

**Comment by mhow2** [comment]
Let's close it for now.
