### ISSUE TITLE
GitLab reader issue

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#155]
When starting a task on a previously imported GitLab project (https://gitlab.ow2.org/sat4j/sat4j) I get:

```
INFO  [ProjectDelta (sat4j,20190301)] (08:02:20): Creating Delta
ERROR [ProjectDelta (sat4j,20190301)] (08:02:25): Delta creation failed.
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.eclipse.scava.platform.bugtrackingsystem.gitlab.GitLabManager.checkHeader(GitLabManager.java:435)
	at org.eclipse.scava.platform.bugtrackingsystem.gitlab.GitLabManager.getAllIssues(GitLabManager.java:220)
	at org.eclipse.scava.platform.bugtrackingsystem.gitlab.GitLabManager.getDelta(GitLabManager.java:92)
	at org.eclipse.scava.platform.bugtrackingsystem.gitlab.GitLabManager.getDelta(GitLabManager.java:1)
	at org.eclipse.scava.platform.delta.bugtrackingsystem.PlatformBugTrackingSystemManager.getDelta(PlatformBugTrackingSystemManager.java:100)
	at org.eclipse.scava.platform.delta.bugtrackingsystem.BugTrackingSystemProjectDelta.<init>(BugTrackingSystemProjectDelta.java:32)
	at org.eclipse.scava.platform.delta.ProjectDelta.create(ProjectDelta.java:65)
	at org.eclipse.scava.platform.osgi.analysis.ProjectAnalyser.executeAnalyse(ProjectAnalyser.java:102)
	at org.eclipse.scava.platform.osgi.services.WorkerExecutor.run(WorkerExecutor.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
ERROR [ProjectExecutor (w2:satj:dd)] (08:02:25): Project delta creation failed. Aborting.
```

Mongo content for bugtracker config is : 

```json
	"bugTrackingSystems" : [
		{
			"_id" : "41d3ee56-5232-481c-a140-184eeb9fc812",
			"_type" : "org.eclipse.scava.repository.model.gitlab.GitLabTracker",
			"persons" : [ ],
			"_superTypes" : [
				"org.eclipse.scava.repository.model.gitlab.BugTrackingSystem"
			],
			"url" : "https://gitlab.ow2.org/api/v4/projects/sat4j%2Fsat4j/issues",
			"_ossmeterId" : "https://gitlab.ow2.org/api/v4/projects/sat4j%2Fsat4j/issues:sat4j%2Fsat4j:gitlab",
			"project_id" : "sat4j%2Fsat4j"
		}
	],

```

**Comment by creat89** [comment]
@mhow2, I'm guessing that the error is due to the lack of the personal access token for GitLab. @Danny2097 can explain more why it is necessary this for accessing the GitLab API. However, in the meaintime, can you add a personal token to GitLab and try it again?

**Comment by Danny2097** [comment]
@mhow2 [here ](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html) is a link to  information relating to a personal access token and how to obtain one.

**Comment by mhow2** [comment]
Thanks. But I now how to obtain a personal token, but that's not the problem here. In addition I'm unsure why we would need a personal token ? If it is about API calls rate limit - like it is for github - I'm not even sure that using a token would overcome the limits. 

this being said, I notice that:
- The exception is not handled
- I'm not told which property name I have to add. (I use `githubToken` for github)
- Remember that I am and end user who's using the Admin UI to provision/configure SCAVA projects

**Comment by Danny2097** [comment]
Hi @mhow2 please see below. 

> The exception is not handled

Thank you for pointing this out. I will begin work on a patch to handle this exception within the Git Lab reader. In the meantime @creat89 has added a _temporary_ hot-fix to the gitlab importer to help prevent this.

> In addition I'm unsure why we would need a personal token ?

We utilise the personal access token as a form of authentication for making calls to certain endpoints. For some Git Lab end points no authentication is required when a call. However, for other calls such as _Issues_, Git Lab requires the call to be authenticated. Meaning the personal access token is required in order for this particular reader to operate correctly.

Unfortunately for us, the each repository has its own unique traits that result in each repository requiring its own set of properties that have to be populated prior to analysing a project.

> I'm not told which property name I have to add. 

We have specified in the models associated with the gitlab reader what properties are required for the reader to operate. I am personally not familiar with how this information is passed to / handled by UI as this is developed by another partner. However,  I know that @tdegueul has developed the GitLab importer, maybe he could be of further assistance to us?

**Comment by mhow2** [comment]
> We have specified in the models associated with the gitlab reader what properties are required for the reader to operate. I am personally not familiar with how this information is passed to / handled by UI as this is developed by another partner. However, I know that @tdegueul has developed the GitLab importer, maybe he could be of further assistance to us?

@ambpro : could you have a look for a way to connect the work done by @crossminer/ehu to the admin UI please ?

**Comment by creat89** [comment]
Hello @mhow2, I have modified the code that handles a GitLab token. So, now (or as soon Jenkins finishes building the platform), you can add the properties the token using the property name `gitlabToken`. And in consequence test the big tracker reader that we have developed for GitLab.

**Comment by mhow2** [comment]
With the latest build (nb 146 in the CI) I get the following error when starting a task on a GitLab project:

```
INFO  [ProjectExecutor (w2:satj:all)] (08:41:43): Beginning execution.
INFO  [ProjectExecutor (w2:satj:all)] (08:41:43): ProjectAnalyser( Project 'satj' Worker 'w2' AnalysisTask : satj:all)
INFO  [ProjectExecutor (w2:satj:all)] (08:41:43): Loading all metricProviders
INFO  [ProjectExecutor (w2:satj:all)] (08:41:43): Loading all metricProviders is done in 1 ms
INFO  [ProjectExecutor (w2:satj:all)] (08:41:43): Extracting Factoid metrics of all metricProviders
INFO  [ProjectExecutor (w2:satj:all)] (08:41:43): Extracting Factoid metricProviders is done.
INFO  [ProjectExecutor (w2:satj:all)] (08:41:43): Creating metric branches.
INFO  [ProjectExecutor (w2:satj:all)] (08:41:43): Creating metric branches is done in 7 ms
INFO  [ProjectExecutor (w2:satj:all)] (08:41:43): Dates: 100
INFO  [ProjectExecutor (w2:satj:all)] (08:41:43): Project satjTask execution ( satj:all : Date 20190101 )
INFO  [AnalysisSchedulingService] (08:41:43): Starting new daily execution AnalysisTask 'satj:all'
INFO  [AnalysisSchedulingService] (08:41:43): Starting new daily execution AnalysisTask 'satj:all' is done.
INFO  [ProjectExecutor (w2:satj:all)] (08:41:43): Date: 20190101, project: sat4j
INFO  [ProjectDelta (sat4j,20190101)] (08:41:43): Creating Delta
ERROR [ProjectDelta (sat4j,20190101)] (08:41:48): Delta creation failed.
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.eclipse.scava.platform.bugtrackingsystem.gitlab.GitLabManager.checkHeader(GitLabManager.java:435)
	at org.eclipse.scava.platform.bugtrackingsystem.gitlab.GitLabManager.getAllIssues(GitLabManager.java:220)
	at org.eclipse.scava.platform.bugtrackingsystem.gitlab.GitLabManager.getDelta(GitLabManager.java:92)
	at org.eclipse.scava.platform.bugtrackingsystem.gitlab.GitLabManager.getDelta(GitLabManager.java:1)
	at org.eclipse.scava.platform.delta.bugtrackingsystem.PlatformBugTrackingSystemManager.getDelta(PlatformBugTrackingSystemManager.java:100)
	at org.eclipse.scava.platform.delta.bugtrackingsystem.BugTrackingSystemProjectDelta.<init>(BugTrackingSystemProjectDelta.java:32)
	at org.eclipse.scava.platform.delta.ProjectDelta.create(ProjectDelta.java:65)
	at org.eclipse.scava.platform.osgi.analysis.ProjectAnalyser.executeAnalyse(ProjectAnalyser.java:102)
	at org.eclipse.scava.platform.osgi.services.WorkerExecutor.run(WorkerExecutor.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
ERROR [ProjectExecutor (w2:satj:all)] (08:41:48): Project delta creation failed. Aborting.
INFO  [WorkerService] (08:41:48): Completing AnalysisTask on Worker 'w2'
INFO  [WorkerService] (08:41:48): Completing  AnalysisTask 'satj:all' on Worker 'w2' done
INFO  [WorkerExecutor] (08:41:58): Worker 'w2' Waiting new Tasks
```

**Comment by mhow2** [comment]
This might be related to the fact that the project was previously existing in the platform with existing analysis data in db. I need to reproduce with an empty db.

**Comment by mhow2** [comment]
Sorry but I'm not able to have the GitLab reader to work. The above` java.lang.NumberFormatException: null` still happen in latest build. Do you have further info ?

**Comment by creat89** [comment]
@Danny2097, the issue came from the fact that there can be host different than gitlab.com; in the case of OW2, it is gitlab.ow2.org. I have modified in https://github.com/crossminer/scava/commit/9e2bde41b1ea74f22d647ffa32532f7d4f4d79cc the behavior of the reader to use the URL instead of the projectId for retrieving the data. The changes that you have done in the header checking are still needed I guess.

**Comment by mhow2** [comment]
@creat89, @Danny2097 : I still have the following issue (with GitLab token registered *before* project creation):

```
ERROR [ProjectDelta (asm,20180101)] (08:37:17): Delta creation failed.
java.lang.NumberFormatException: null
    at java.lang.Integer.parseInt(Integer.java:542)
    at java.lang.Integer.parseInt(Integer.java:615)
    at org.eclipse.scava.platform.bugtrackingsystem.gitlab.GitLabManager.checkHeader(GitLabManager.java:440)
    at org.eclipse.scava.platform.bugtrackingsystem.gitlab.GitLabManager.getAllIssues(GitLabManager.java:218)
    at org.eclipse.scava.platform.bugtrackingsystem.gitlab.GitLabManager.getDelta(GitLabManager.java:92)
    at org.eclipse.scava.platform.bugtrackingsystem.gitlab.GitLabManager.getDelta(GitLabManager.java:1)
    at org.eclipse.scava.platform.delta.bugtrackingsystem.PlatformBugTrackingSystemManager.getDelta(PlatformBugTrackingSystemManager.java:100)
    at org.eclipse.scava.platform.delta.bugtrackingsystem.BugTrackingSystemProjectDelta.<init>(BugTrackingSystemProjectDelta.java:32)
    at org.eclipse.scava.platform.delta.ProjectDelta.create(ProjectDelta.java:65)
    at org.eclipse.scava.platform.osgi.analysis.ProjectAnalyser.executeAnalyse(ProjectAnalyser.java:102)
    at org.eclipse.scava.platform.osgi.services.WorkerExecutor.run(WorkerExecutor.java:55)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
ERROR [ProjectExecutor (w2:asm:all)] (08:37:17): Project delta creation failed. Aborting.
INFO  [WorkerService] (08:37:17): Completing AnalysisTask on Worker 'w2'
```

**Comment by mhow2** [comment]
> > We have specified in the models associated with the gitlab reader what properties are required for the reader to operate. I am personally not familiar with how this information is passed to / handled by UI as this is developed by another partner. However, I know that @tdegueul has developed the GitLab importer, maybe he could be of further assistance to us?
> 
> @ambpro : could you have a look for a way to connect the work done by @crossminer/ehu to the admin UI please ?

@ambpro , please, can you take a look.

**Comment by mhow2** [comment]
Today I get this when running a task on https://gitlab.ow2.org/asm/asm and a valid token  (not sure it is related ) :

```
Metric: org.eclipse.scava.metricprovider.historic.configuration.puppet.dependencies failed to retrieve the transient metric it needs!
0 patches captured
        usedNobc.getBugTrackerData().size(): 1
        usedNobc.getBugTrackerData().size(): 1
Unable to init server: Could not connect: Connection refused
Eclipse:
GTK+ Version Check
Eclipse:
JVM terminated. Exit code=255
/usr/bin/java
-Xmx8g
-jar /ossmeter//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
-os linux
-ws gtk
-arch x86_64
-showsplash
-launcher /ossmeter/eclipse
-name Eclipse
--launcher.library /ossmeter//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.300.v20150602-1417/eclipse_1612.so
-startup /ossmeter//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
--launcher.overrideVmargs
-exitdata 0
-master
-apiServer
-worker w1
-config prop.properties
-vm /usr/bin/java
-vmargs
-Xmx8g
-jar /ossmeter//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar 
```
Also attaching the internal MP's log : 
[metric-pf.log](https://github.com/crossminer/scava/files/3206782/metric-pf.log)

All in all there is no Exception raising anywhere... I don't understand this crash.

**Comment by creat89** [comment]
@mhow2, I don't think it is related to the GitLab reader anymore. For what you're showing in the message there was an issue with the `org.eclipse.scava.metricprovider.historic.configuration.puppet.dependencies`, which couldn't find a metric. I think you should open an issue tagging @blueoly. Have you seen this issue with other metrics but the configuration ones?

**Comment by blueoly** [comment]
@mhow2 @creat89 Hello,

after the revertion of the unsuccessful merge from Amin, the definition of the puppet dependencies metric providers were erased from the feature.xml, so it is possible that the metric failed because of that. I have addressed this late last night (or early this morning, it depends on the perspective) with this commit 765074b. Martin, please rebuild docker containers with the updated images to check if this issue is solved.

**Comment by mhow2** [comment]
hi @blueoly ; I just tested with https://gitlab.ow2.org/sat4j/sat4j on a new deployement (dev branch as usual) and I get:

```
INFO  [WorkerExecutor] (15:36:08): Worker 'w2' Executing sat4j:alld Task
INFO  [WorkerService] (15:36:08): Assigning AnalysisTask 'sat4j:alld' to Worker 'w2'
INFO  [WorkerService] (15:36:08): Assigning AnalysisTask 'sat4j:alld' to Worker 'w2' done.
INFO  [ProjectExecutor (w2:sat4j:alld)] (15:36:08): Beginning execution.
INFO  [ProjectExecutor (w2:sat4j:alld)] (15:36:08): ProjectAnalyser( Project 'sat4j' Worker 'w2' AnalysisTask : sat4j:alld)
INFO  [ProjectExecutor (w2:sat4j:alld)] (15:36:22): Loading all metricProviders
INFO  [ProjectExecutor (w2:sat4j:alld)] (15:36:22): Loading all metricProviders is done in 53 ms
INFO  [ProjectExecutor (w2:sat4j:alld)] (15:36:22): Extracting Factoid metrics of all metricProviders
INFO  [ProjectExecutor (w2:sat4j:alld)] (15:36:22): Extracting Factoid metricProviders is done.
INFO  [ProjectExecutor (w2:sat4j:alld)] (15:36:22): Creating metric branches.
INFO  [ProjectExecutor (w2:sat4j:alld)] (15:36:22): Creating metric branches is done in 11 ms
INFO  [ProjectExecutor (w2:sat4j:alld)] (15:36:22): Dates: 455
INFO  [ProjectExecutor (w2:sat4j:alld)] (15:36:22): Project sat4jTask execution ( sat4j:alld : Date 20180101 )
INFO  [AnalysisSchedulingService] (15:36:22): Starting new daily execution AnalysisTask 'sat4j:alld'
INFO  [AnalysisSchedulingService] (15:36:22): Starting new daily execution AnalysisTask 'sat4j:alld' is done.
INFO  [ProjectExecutor (w2:sat4j:alld)] (15:36:22): Date: 20180101, project: sat4j
INFO  [ProjectDelta (sat4j,20180101)] (15:36:22): Creating Delta
ERROR [ProjectDelta (sat4j,20180101)] (15:36:29): Delta creation failed.
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.eclipse.scava.platform.bugtrackingsystem.gitlab.GitLabManager.checkHeader(GitLabManager.java:425)
	at org.eclipse.scava.platform.bugtrackingsystem.gitlab.GitLabManager.getComments(GitLabManager.java:283)
	at org.eclipse.scava.platform.bugtrackingsystem.gitlab.GitLabManager.getDelta(GitLabManager.java:111)
	at org.eclipse.scava.platform.bugtrackingsystem.gitlab.GitLabManager.getDelta(GitLabManager.java:1)
	at org.eclipse.scava.platform.delta.bugtrackingsystem.PlatformBugTrackingSystemManager.getDelta(PlatformBugTrackingSystemManager.java:100)
	at org.eclipse.scava.platform.delta.bugtrackingsystem.BugTrackingSystemProjectDelta.<init>(BugTrackingSystemProjectDelta.java:32)
	at org.eclipse.scava.platform.delta.ProjectDelta.create(ProjectDelta.java:65)
	at org.eclipse.scava.platform.osgi.analysis.ProjectAnalyser.executeAnalyse(ProjectAnalyser.java:102)
	at org.eclipse.scava.platform.osgi.services.WorkerExecutor.run(WorkerExecutor.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
ERROR [ProjectExecutor (w2:sat4j:alld)] (15:36:29): Project delta creation failed. Aborting.
INFO  [WorkerService] (15:36:29): Completing AnalysisTask on Worker 'w2'
INFO  [WorkerService] (15:36:29): Completing  AnalysisTask 'sat4j:alld' on Worker 'w2' done
```

If you look at your Slack PMs, I provided a gitlabToken - that would help you reproduce the things up directly on your side.

**Comment by creat89** [comment]
@mhow2 If you have that issue, that concerns us, as you can see the error is at the delta creation. I'll check the issue.

**Comment by creat89** [comment]
@mhow2, I tested by myself the code at that days and for that project, and I couldn't reproduce the issue. It is weird that the server didn't return that part of the headers correctly. I have pushed a commit https://github.com/crossminer/scava/commit/70a07f7d73c8eb2e98ebc664e3c2bd14c63e6636 which should solve the issue once for all. Moreover, print on the logger the issue encountered.
