### ISSUE TITLE
java.lang.NullPointerException with "codedetection"

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#167]
Starting from a scratch docker stack, I'm facing this exception when running an analysis on imported GitHub : https://github.com/INRIA/spoon.git

```
INFO  [AnalysisSchedulingService] (08:46:22): Starting find out MetricExecution 'org.eclipse.scava.metricprovider.trans.detectingcode.DetectingCodeTransMetricProvider' on Project 'spoon'
INFO  [MetricListExecutor (spoon, 20181102)] (08:46:22): Starting Metric Execution (codedetection).
INFO  [nlp.classifiers.codedetector] (08:46:22): Searching the model at /ossmeter/plugins/org.eclipse.scava.nlp.classifiers.codedetector_1.0.0.201904091909.jarmodel/model_Mixed_sentences_all.bin
ERROR [MetricListExecutor (spoon, 20181102)] (08:46:22): Exception thrown during metric provider execution (codedetection).
java.lang.NullPointerException
	at org.eclipse.scava.nlp.classifiers.codedetector.CodeDetector.predictGeneral(CodeDetector.java:158)
	at org.eclipse.scava.nlp.classifiers.codedetector.CodeDetector.lambda$0(CodeDetector.java:129)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:590)
	at org.eclipse.scava.nlp.classifiers.codedetector.CodeDetector.predict(CodeDetector.java:127)
	at org.eclipse.scava.nlp.classifiers.codedetector.CodeDetector.predict(CodeDetector.java:111)
	at org.eclipse.scava.metricprovider.trans.detectingcode.DetectingCodeTransMetricProvider.applyCodeDetector(DetectingCodeTransMetricProvider.java:184)
	at org.eclipse.scava.metricprovider.trans.detectingcode.DetectingCodeTransMetricProvider.applyCodeDetector(DetectingCodeTransMetricProvider.java:163)
	at org.eclipse.scava.metricprovider.trans.detectingcode.DetectingCodeTransMetricProvider.measure(DetectingCodeTransMetricProvider.java:124)
	at org.eclipse.scava.metricprovider.trans.detectingcode.DetectingCodeTransMetricProvider.measure(DetectingCodeTransMetricProvider.java:1)
	at org.eclipse.scava.platform.osgi.analysis.MetricListExecutor.run(MetricListExecutor.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
INFO  [AnalysisSchedulingService] (08:46:22): Ending MetricExecution 'org.eclipse.scava.metricprovider.trans.detectingcode.DetectingCodeTransMetricProvider'
```

Attached the whole logs [metric-pf.log.gz](https://github.com/crossminer/scava/files/3062981/metric-pf.log.gz)

**Comment by creat89** [comment]
I have a fix for that issue on that classifier. However, this means that all the classifiers will have a similar issue. But for those, the solution, I still don't have it and might be harder than expected to solve it.

**Comment by creat89** [comment]
I have solved the bug in commit https://github.com/crossminer/scava/commit/4ac53b04c2886b423d680e267727fccf06769016 as some others with the same nature.
