### ISSUE TITLE
error 500 when requesting .../m/ratioUnusedOSGiImportedPackages

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#168]
In the latest build , when I look to http://scava-dev.ow2.org:8182/projects/p/xwiki/m/ratioUnusedOSGiImportedPackages I get an error 500

Which is not the case for others metrics

The project is https://github.com/xwiki/xwiki-platform

If I look to the container output, I get this:

```
oss-app_1         | ERROR: Could not find collection: trans.rascal.dependency.osgi.ratioUnusedOSGiImportedPackages
oss-app_1         | Apr 11, 2019 8:31:10 AM org.restlet.resource.ServerResource doCatch
oss-app_1         | WARNING: Exception or error caught in server resource
oss-app_1         | Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfi
lling the request
oss-app_1         |     at org.restlet.resource.ServerResource.doHandle(ServerResource.java:540)
oss-app_1         |     at org.restlet.resource.ServerResource.get(ServerResource.java:743)
...
oss-app_1         | Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to com.mongodb.BasicDBList
oss-app_1         |     at org.eclipse.scava.platform.visualisation.Chart.createDatatable(Chart.java:84)
oss-app_1         |     at org.eclipse.scava.platform.visualisation.MetricVisualisation.visualise(MetricVisualisation.java:80)
oss-app_1         |     at org.eclipse.scava.platform.client.api.MetricVisualisationResource.doRepresent(MetricVisualisationResource.java:75)
oss-app_1         |     at org.eclipse.scava.platform.client.api.AbstractApiResource.represent(AbstractApiResource.java:61)
oss-app_1         |     at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
oss-app_1         |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
oss-app_1         |     at java.lang.reflect.Method.invoke(Method.java:498)
oss-app_1         |     at org.restlet.resource.ServerResource.doHandle(ServerResource.java:524)
oss-app_1         |     ... 47 more
oss-app_1         |
oss-app_1         | Apr 11, 2019 8:31:10 AM org.restlet.engine.log.LogFilter afterHandle

```

Any clue ?

**Comment by mhow2** [comment]
Same for `ratioOptionalMavenDependenciesTimeLine`

**Comment by tdegueul** [comment]
This is a known bug since the refactoring of metric / metricVisualization IDs by @ambpro. I'm on it.
