### ISSUE TITLE
JIRA reader not working with Atlassian's SaaS

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#176]
It seems the system is not able to retrieve issues at the endpoint/query https://bonita.atlassian.net/rest/api/2/search?startAt=0&maxResults=50&jql=project+%3D+%22BBPMC%22+AND+%28updated+%3E%3D+%222019%2F04%2F01+00%3A00%22+OR+created+%3E%3D+%222019%2F04%2F01+00%3A00%22%29&fields=*all%2C-issuelinks

The above query works in a browser when you are authenticated to the service. But in the reader we get a 401 which means there could be issue with authentication.

The issue tracker is at https://bonita.atlassian.net/projects/BBPMC/issues/

By the way, it would be nice if the error could be raised back to the API or UI to inform the user what's the error is.

```
ERROR [ProjectDelta (bonita,20190401)] (08:47:04): Delta creation failed.
java.lang.RuntimeException: java.lang.RuntimeException: Error executing call to webservice. [401,https://bonita.atlassian.net/rest/api/2/search?startAt=0&maxResults=50&jql=project+%3D+%22BBPMC%22+AND+%28updated+%3E%3D+%222019%2F04%2F01+00%3A00%22+OR+created+%3E%3D+%222019%2F04%2F01+00%3A00%22%29&fields=*all%2C-issuelinks]
	at org.eclipse.scava.platform.bugtrackingsystem.jira.api.JiraIssueIterator.getNextPage(JiraIssueIterator.java:52)
	at org.eclipse.scava.platform.bugtrackingsystem.jira.api.JiraIssueIterator.hasNext(JiraIssueIterator.java:37)
	at org.eclipse.scava.platform.bugtrackingsystem.cache.Cache.cacheItems(Cache.java:105)
	at org.eclipse.scava.platform.bugtrackingsystem.cache.Cache.update(Cache.java:69)
	at org.eclipse.scava.platform.bugtrackingsystem.cache.Cache.getItemsAfterDate(Cache.java:53)
	at org.eclipse.scava.platform.bugtrackingsystem.jira.JiraManager.getDelta(JiraManager.java:94)
	at org.eclipse.scava.platform.bugtrackingsystem.jira.JiraManager.getDelta(JiraManager.java:1)
	at org.eclipse.scava.platform.delta.bugtrackingsystem.PlatformBugTrackingSystemManager.getDelta(PlatformBugTrackingSystemManager.java:100)
	at org.eclipse.scava.platform.delta.bugtrackingsystem.BugTrackingSystemProjectDelta.<init>(BugTrackingSystemProjectDelta.java:32)
	at org.eclipse.scava.platform.delta.ProjectDelta.create(ProjectDelta.java:65)
	at org.eclipse.scava.platform.osgi.analysis.ProjectAnalyser.executeAnalyse(ProjectAnalyser.java:102)
	at org.eclipse.scava.platform.osgi.services.WorkerExecutor.run(WorkerExecutor.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Error executing call to webservice. [401,https://bonita.atlassian.net/rest/api/2/search?startAt=0&maxResults=50&jql=project+%3D+%22BBPMC%22+AND+%28updated+%3E%3D+%222019%2F04%2F01+00%3A00%22+OR+created+%3E%3D+%222019%2F04%2F01+00%3A00%22%29&fields=*all%2C-issuelinks]
	at org.eclipse.scava.platform.bugtrackingsystem.jira.api.JiraRestClient.executeRestCall(JiraRestClient.java:183)
	at org.eclipse.scava.platform.bugtrackingsystem.jira.api.JiraRestClient.search(JiraRestClient.java:166)
	at org.eclipse.scava.platform.bugtrackingsystem.jira.api.JiraRestClient.search(JiraRestClient.java:156)
	at org.eclipse.scava.platform.bugtrackingsystem.jira.api.JiraIssueIterator.getNextPage(JiraIssueIterator.java:50)
	... 14 more

```

**Comment by mhow2** [comment]
What about that one ?

**Comment by mhow2** [comment]
Hi, do we have any news on this ?

**Comment by creat89** [comment]
I couldn't reproduce the issue and I don't know why JIRA server should return an error 401 when the data is openly accessible. If the reader would have reached the rate limit of calls, the error would be 429. Nonetheless, I've pushed some commits, as it seems that the JIRA reader was broken after I modified some versions of their dependencies. But, this issue was much before that change.

**Comment by mhow2** [comment]
I just tested again and get the same error. As far as I can tell It only happened to me with Atlassian's SaaS. I'm running the analysis with all metrics enabled over year 2018. Original issue description is still valid.

**Comment by creat89** [comment]
Are you using authentication for the JIRA Reader? If so, can you check your credentials? Especially your username. When I tested them, I didn't use any authentication. 

https://community.atlassian.com/t5/Jira-questions/JIRA-Rest-API-authentication-always-returns-401-unauthorized/qaq-p/187181

**Comment by mhow2** [comment]
Thanks.

> (from the answer) The password is NOT your password to login, but an API token

... So it might be the issue for SaaS. I'll test that.

> When I tested them, I didn't use any authentication.

but we need both to work at the end :)

**Comment by mhow2** [comment]
Now I bump on #276 so I suppose for the current issue it's a good news : it means the API token works :)
