### ISSUE TITLE
Client Connection Failure

### ISSUE THREAD

**Issue by MarcioMateus** [crossminer/scava#297]
When analysing the project  https://gitlab.ow2.org/clif/clif-legacy, using an analysis task form 30/01/2018 to 31/01/2018 with all metrics. The task froze for some minutes at -100% (minus!) but started and then crashed at -22%.

You can see below the stack trace of the metrics. Several metrics presented some kind of error.
[stack-trace.json.txt](https://github.com/crossminer/scava/files/3297736/stack-trace.json.txt)

The following errors where found on `oss-app` log:
```
oss-app_1         | Exception in thread "pool-9-thread-3" INFO  [MetricListExecutor (cliflegacy, 20180130)] (15:13:48): Starting execution AnalysisTask 'cliflegacy:task4' with MetricExecution 'trans.rascal.OO.java.A-Java'
oss-app_1         | INFO  [MetricListExecutor (cliflegacy, 20180130)] (15:13:48): Adding dependencies to metricProvider 'trans.rascal.OO.java.A-Java' into project 'cliflegacy'
oss-app_1         | INFO  [MetricListExecutor (cliflegacy, 20180130)] (15:13:48): Added dependencies to metricProvider 'trans.rascal.OO.java.A-Java' into project 'cliflegacy'
oss-app_1         | INFO  [AnalysisSchedulingService] (15:13:48): Starting MetricExecution 'trans.rascal.OO.java.A-Java'
oss-app_1         | INFO  [AnalysisSchedulingService] (15:13:48): Update the worker 'w1' heartBeat Mon Jun 17 15:13:48 UTC 2019'
oss-app_1         | INFO  [AnalysisSchedulingService] (15:13:48): Starting MetricExecution 'trans.rascal.OO.java.A-Java' is done.
oss-app_1         | INFO  [AnalysisSchedulingService] (15:13:48): Starting find out MetricExecution 'trans.rascal.OO.java.A-Java' on Project 'cliflegacy'
oss-app_1         | INFO  [MetricListExecutor (cliflegacy, 20180130)] (15:13:48): Starting Metric Execution (A_Java).
oss-app_1         | java.lang.StackOverflowError
oss-app_1         | 	at java.lang.Class.searchMethods(Class.java:3003)
oss-app_1         | 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
oss-app_1         | 	at java.lang.Class.getMethod0(Class.java:3018)
oss-app_1         | 	at java.lang.Class.getMethod(Class.java:1784)
oss-app_1         | 	at org.apache.commons.logging.LogFactory.directGetContextClassLoader(LogFactory.java:847)
oss-app_1         | 	at org.apache.commons.logging.LogFactory$1.run(LogFactory.java:817)
oss-app_1         | 	at java.security.AccessController.doPrivileged(Native Method)
oss-app_1         | 	at org.apache.commons.logging.LogFactory.getContextClassLoaderInternal(LogFactory.java:814)
oss-app_1         | 	at org.apache.commons.logging.LogFactory.getFactory(LogFactory.java:421)
oss-app_1         | 	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:657)
oss-app_1         | 	at org.apache.http.impl.nio.client.MainClientExec.<init>(MainClientExec.java:82)
oss-app_1         | 	at org.apache.http.impl.nio.client.HttpAsyncClientBuilder.build(HttpAsyncClientBuilder.java:847)
oss-app_1         | 	at org.elasticsearch.client.RestClientBuilder$2.run(RestClientBuilder.java:216)
oss-app_1         | 	at org.elasticsearch.client.RestClientBuilder$2.run(RestClientBuilder.java:213)
oss-app_1         | 	at java.security.AccessController.doPrivileged(Native Method)
oss-app_1         | 	at org.elasticsearch.client.RestClientBuilder.createHttpClient(RestClientBuilder.java:213)
oss-app_1         | 	at org.elasticsearch.client.RestClientBuilder.access$000(RestClientBuilder.java:42)
oss-app_1         | 	at org.elasticsearch.client.RestClientBuilder$1.run(RestClientBuilder.java:186)
oss-app_1         | 	at org.elasticsearch.client.RestClientBuilder$1.run(RestClientBuilder.java:183)
oss-app_1         | 	at java.security.AccessController.doPrivileged(Native Method)
oss-app_1         | 	at org.elasticsearch.client.RestClientBuilder.build(RestClientBuilder.java:183)
oss-app_1         | 	at org.eclipse.scava.index.indexer.IndexerSingleton.createHighLevelClientLocal(IndexerSingleton.java:181)
oss-app_1         | 	at org.eclipse.scava.index.indexer.IndexerSingleton.createHighLevelClientLocal(IndexerSingleton.java:202)
oss-app_1         | 	at org.eclipse.scava.index.indexer.IndexerSingleton.createHighLevelClientLocal(IndexerSingleton.java:202)
```

But before this error, if find multiple times this message:

```
oss-app_1         | INFO  [Indexer Singleton] (15:13:47): Client Connection Failure
oss-app_1         | INFO  [Indexer Singleton] (15:13:47): Client Connection Failure
oss-app_1         | INFO  [Indexer Singleton] (15:13:47): java.io.IOException: Connection refused
```

I don't know which client is having problems...

This behaviour as detected when trying to reproduce https://github.com/crossminer/scava/issues/276

**Comment by Danny2097** [comment]
In https://github.com/crossminer/scava/commit/f204c8c8a63f5a00bbfac4746653b365880a69a2, I  removed the 'fall back' mechanism which creates a local client (which connects to a local ES cluster) - since this was only used during development. This should prevent the error above.

However this mechanism should only be triggered when the client is unable to connect to the ES cluster deployed with platform.

**Comment by MarcioMateus** [comment]
Hi @Danny2097 thanks for the feedback. Actually when I saw this behaviour, the ES container was not running.

So for the this metric-provider to work as expected he should also deploy the ES instance? Or is only required for testing?

**Comment by Danny2097** [comment]
@MarcioMateus for the indexing to work, ES should already be running.
