### ISSUE TITLE
error in NewVersionMavenTransMetricProvider

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#309]
Project: https://github.com/bonitasoft/bonita-studio
Timespan : 2018
Metrics: all enabled

(The same seems to happen with `metricprovider.trans.newversion.osgi.NewVersionOsgiTransMetricProvider`)

```
INFO  [MetricListExecutor (BonitaStudio, 20180104)] (07:20:32): Starting Metric Execution (newVersionMaven).
ERROR [metricprovider.trans.newversion.maven.NewVersionMavenTransMetricProvider] (07:20:32): unexpected IO exception while measuring
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at org.eclipse.scava.metricprovider.trans.newversion.maven.NewVersionMavenTransMetricProvider.measure(NewVersionMavenTransMetricProvider.java:92)
        at org.eclipse.scava.metricprovider.trans.newversion.maven.NewVersionMavenTransMetricProvider.measure(NewVersionMavenTransMetricProvider.java:1)
        at org.eclipse.scava.platform.osgi.analysis.MetricListExecutor.run(MetricListExecutor.java:103)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
ERROR [MetricListExecutor (BonitaStudio, 20180104)] (07:20:32): Exception thrown during metric provider execution (newVersionMaven).
java.lang.RuntimeException: java.net.ConnectException: Connection refused (Connection refused)
        at org.eclipse.scava.metricprovider.trans.newversion.maven.NewVersionMavenTransMetricProvider.measure(NewVersionMavenTransMetricProvider.java:128)
        at org.eclipse.scava.metricprovider.trans.newversion.maven.NewVersionMavenTransMetricProvider.measure(NewVersionMavenTransMetricProvider.java:1)
        at org.eclipse.scava.platform.osgi.analysis.MetricListExecutor.run(MetricListExecutor.java:103)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at org.eclipse.scava.metricprovider.trans.newversion.maven.NewVersionMavenTransMetricProvider.measure(NewVersionMavenTransMetricProvider.java:92)
        ... 5 more
INFO  [AnalysisSchedulingService] (07:20:32): Ending MetricExecution 'org.eclipse.scava.metricprovider.trans.newversion.maven.NewVersionMavenTransMetricProvider'
INFO  [AnalysisSchedulingService] (07:20:32): Ending MetricExecution 'org.eclipse.scava.metricprovider.trans.newversion.maven.NewVersionMavenTransMetricProvider' is done.
INFO  [MetricListExecutor (BonitaStudio, 20180104)] (07:20:32): Ending execution AnalysisTask 'BonitaStudio:task' with MetricExecution 'org.eclipse.scava.metricprovider.trans.newversion.maven.NewVersionMavenTransMetricProvider' done in 21 ms

```

**Comment by mhow2** [comment]
Hi @tdegueul, are you the one this issue ?

**Comment by blueoly** [comment]
Hi @mhow2 ! I am responsible for this. Could you please tell me the address of the CROSSMINER instance, where the error happened, if of course the instance is public.

**Comment by mhow2** [comment]
@blueoly : Hi ! I'm afraid that I have wiped the instance since then. In the log pasted above you have the day of analysis when it happened. Can you tell me what you need exactly ?

**Comment by blueoly** [comment]
I need an instance that this error happens because I cannot reproduce this issue. At my instances, it runs fine.

**Comment by mhow2** [comment]
I'm closing it and will reopen when I get time to reproduce.

**Comment by mhow2** [comment]
I just reproduced with project XWIKI.
See the log file [metric-pf.log](https://github.com/crossminer/scava/files/3599665/metric-pf.log) at line ~673

**Comment by blueoly** [comment]
Hi @mhow2 . I examined this issue extensively during the previous week. I never achieved to reproduce this bug. In every instance of the platform that I tried, everything ran smoothly. That happened in the two beta instances too. Please, try to reproduce it once again in your instance.

I can make a guess about why you came across at first place. My metric providers about these metrics, call inside them the :8182 metric service. I tried some times to call http://scava-dev.ow2.org:8182/ . One or two times, the link seemed to be offline. Maybe, the time that you ran my metrics and you found the bug, was a time that the :8182 service was out.

**Comment by mhow2** [comment]
Thank you for taking care @blueoly.
I have updated to:
```
root@257ee21e79aa:~# cat /version 
dev-66ccd1c595f5181c037307603de833756d0999b8

```
I just created a new project in the admin UI : http://scava-dev.ow2.org:5601/#/project/configure/XWikiTest , and ticket the metrics related to "maven".

I can see the errors. Notice that the task run on a slave. Maybe I'm doing something wrong ?

```
INFO  [GitWorkingCopyManager] (07:42:23): Checkout https://github.com/xwiki/xwiki-platform.git in revision 89bf7ca9aae77cd6080989385aae6d47511dc164
INFO  [MetricListExecutor (XWikiTest, 20180716)] (07:42:23): Starting Metric Execution (allMavenDependencies).
INFO  [MetricListExecutor (XWikiTest, 20180716)] (07:42:23): Starting Metric Execution (newVersionMaven).
ERROR [metricprovider.trans.newversion.maven.NewVersionMavenTransMetricProvider] (07:42:23): unexpected IO exception while measuring
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at org.eclipse.scava.metricprovider.trans.newversion.maven.NewVersionMavenTransMetricProvider.measure(NewVersionMavenTransMetricProvider.java:92)
	at org.eclipse.scava.metricprovider.trans.newversion.maven.NewVersionMavenTransMetricProvider.measure(NewVersionMavenTransMetricProvider.java:1)
	at org.eclipse.scava.platform.osgi.analysis.MetricListExecutor.run(MetricListExecutor.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
ERROR [MetricListExecutor (XWikiTest, 20180716)] (07:42:23): Exception thrown during metric provider execution (newVersionMaven).
java.lang.RuntimeException: java.net.ConnectException: Connection refused (Connection refused)
	at org.eclipse.scava.metricprovider.trans.newversion.maven.NewVersionMavenTransMetricProvider.measure(NewVersionMavenTransMetricProvider.java:128)
	at org.eclipse.scava.metricprovider.trans.newversion.maven.NewVersionMavenTransMetricProvider.measure(NewVersionMavenTransMetricProvider.java:1)
	at org.eclipse.scava.platform.osgi.analysis.MetricListExecutor.run(MetricListExecutor.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at org.eclipse.scava.metricprovider.trans.newversion.maven.NewVersionMavenTransMetricProvider.measure(NewVersionMavenTransMetricProvider.java:92)
	... 5 more

```
