### ISSUE TITLE
Cannot create analysis tasks in certain projects

### ISSUE THREAD

**Issue by blueoly** [crossminer/scava#325]
I have tried to create analysis tasks in the public beta instance http://beta.crossminer.org:5601 but in some projects this was impossible, for example grimoirelab-elk.

The log from the oss-app container gives back this:

Jul 26, 2019 11:11:33 AM org.restlet.engine.log.LogFilter afterHandle
INFO: 2019-07-26	11:11:33	172.18.0.11	-	172.18.0.7	8182	GET	/analysis/tasks/project/grimoirelabelk	-	500	486	0	3	http://oss-app:8182	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36	http://beta.crossminer.org:5601/
Jul 26, 2019 11:11:33 AM org.restlet.resource.ServerResource doCatch
WARNING: Exception or error caught in server resource
Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:540)
	at org.restlet.resource.ServerResource.get(ServerResource.java:743)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:618)
	at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:679)
	at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:357)
	at org.restlet.resource.ServerResource.handle(ServerResource.java:1044)
	at org.restlet.resource.Finder.handle(Finder.java:236)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:75)
	at org.restlet.Application.handle(Application.java:385)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.Component.handle(Component.java:408)
	at org.restlet.Server.handle(Server.java:507)
	at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)
	at org.restlet.ext.jetty.JettyServerHelper$WrappedServer.handle(JettyServerHelper.java:273)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException

**Comment by ambpro** [comment]
Hello @blueoly,

By looking on the stacktrace, It seems that the metric-platform rest APIs endpoints failed to start correctly. I got the following 500 errors on the browser devtool console when I entered on the admin-ui projects view.

![beta crossminer-1](https://user-images.githubusercontent.com/35226648/63264165-ae79bd00-c28a-11e9-9eb6-b14cb77e632c.png)

At the same time, I launched a fresh instance from the scava-deployment (Latest commit 35e7d18 `dev` branch), playing with the [grimoirelab-elk](https://github.com/chaoss/grimoirelab-elk) project. The result, I couldn't replicate the issue.

![grimoirelab-elk
](https://user-images.githubusercontent.com/35226648/63270193-f94e0180-c297-11e9-94c3-aa1feed9f94c.png)

ICYMI, a couple months ago we did some refactoring on the scava analysis data model. So, the data dumps from [M24](http://ci3.castalia.camp/dl/M24/) is outdated and I suggest you to get ride of them. 

Please, let me know if this could help!

**Comment by ambpro** [comment]
@blueoly, any updates about this issue? 
Otherwise, we could close it ?!

**Comment by blueoly** [comment]
Hi @ambpro . Sorry for the late answer. Yes, we can close the issue.
