### ISSUE TITLE
Hard-coded access to 127.0.0.1:27017

### ISSUE THREAD

**Issue by MarcioMateus** [crossminer/scava#5]
In docker deployment, the following exceptions appear:

```
oss-app_1    | WARNING: Exception executing isMaster command on /127.0.0.1:27017
oss-app_1    | java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused (Connection refused)
oss-app_1    | 	at com.mongodb.DBPort._open(DBPort.java:214)
oss-app_1    | 	at com.mongodb.DBPort.go(DBPort.java:107)
oss-app_1    | 	at com.mongodb.DBPort.go(DBPort.java:88)
oss-app_1    | 	at com.mongodb.DBPort.findOne(DBPort.java:143)
oss-app_1    | 	at com.mongodb.DBPort.runCommand(DBPort.java:148)
oss-app_1    | 	at com.mongodb.DBTCPConnector.initDirectConnection(DBTCPConnector.java:544)
oss-app_1    | 	at com.mongodb.DBTCPConnector.isMongosConnection(DBTCPConnector.java:369)
oss-app_1    | 	at com.mongodb.Mongo.isMongosConnection(Mongo.java:607)
oss-app_1    | 	at com.mongodb.DBCollection.findOne(DBCollection.java:706)
oss-app_1    | 	at com.mongodb.DBCollection.findOne(DBCollection.java:652)
oss-app_1    | 	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:343)
oss-app_1    | 	at com.mongodb.DBCollection.createIndex(DBCollection.java:467)
oss-app_1    | 	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:543)
oss-app_1    | 	at com.googlecode.pongo.runtime.PongoCollection.createIndex(PongoCollection.java:27)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.trans.model.MeasurementCollection.<init>(MeasurementCollection.java:24)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.trans.model.RascalMetrics.setDb(RascalMetrics.java:39)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.trans.model.RascalMetrics.<init>(RascalMetrics.java:22)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.getMetricResult(RascalMetricProvider.java:375)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.compute(RascalMetricProvider.java:279)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:207)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:1)
oss-app_1    | 	at org.eclipse.scava.platform.osgi.executors.MetricListExecutor.run(MetricListExecutor.java:140)
oss-app_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
oss-app_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
oss-app_1    | 	at java.lang.Thread.run(Thread.java:748)
oss-app_1    | 
oss-db_1     | 2018-04-13T11:53:07.155+0000 I -        [conn11059] end connection 172.19.0.3:47474 (51 connections now open)
oss-app_1    | Apr 13, 2018 11:53:07 AM com.mongodb.DBTCPConnector initDirectConnection
oss-app_1    | WARNING: Exception executing isMaster command on /127.0.0.1:27017
oss-app_1    | java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused (Connection refused)
oss-app_1    | 	at com.mongodb.DBPort._open(DBPort.java:214)
oss-app_1    | 	at com.mongodb.DBPort.go(DBPort.java:107)
oss-app_1    | 	at com.mongodb.DBPort.go(DBPort.java:88)
oss-app_1    | 	at com.mongodb.DBPort.findOne(DBPort.java:143)
oss-app_1    | 	at com.mongodb.DBPort.runCommand(DBPort.java:148)
oss-app_1    | 	at com.mongodb.DBTCPConnector.initDirectConnection(DBTCPConnector.java:544)
oss-app_1    | 	at com.mongodb.DBTCPConnector.checkMaster(DBTCPConnector.java:523)
oss-app_1    | 	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:274)
oss-app_1    | 	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:256)
oss-app_1    | 	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:289)
oss-app_1    | 	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:274)
oss-app_1    | 	at com.mongodb.DBCollection.findOne(DBCollection.java:710)
oss-app_1    | 	at com.mongodb.DBCollection.findOne(DBCollection.java:652)
oss-app_1    | 	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:343)
oss-app_1    | 	at com.mongodb.DBCollection.createIndex(DBCollection.java:467)
oss-app_1    | 	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:543)
oss-app_1    | 	at com.googlecode.pongo.runtime.PongoCollection.createIndex(PongoCollection.java:27)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.trans.model.MeasurementCollection.<init>(MeasurementCollection.java:24)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.trans.model.RascalMetrics.setDb(RascalMetrics.java:39)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.trans.model.RascalMetrics.<init>(RascalMetrics.java:22)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.getMetricResult(RascalMetricProvider.java:375)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.compute(RascalMetricProvider.java:279)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:207)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:1)
oss-app_1    | 	at org.eclipse.scava.platform.osgi.executors.MetricListExecutor.run(MetricListExecutor.java:140)
oss-app_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
oss-app_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
oss-app_1    | 	at java.lang.Thread.run(Thread.java:748)
oss-app_1    | 
oss-db_1     | 2018-04-13T11:53:07.156+0000 I -        [conn11062] end connection 172.19.0.3:47480 (50 connections now open)
oss-app_1    | Apr 13, 2018 11:53:07 AM com.mongodb.DBPortPool gotError
oss-app_1    | WARNING: emptying DBPortPool to /127.0.0.1:27017 b/c of error
oss-app_1    | java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused (Connection refused)
oss-app_1    | 	at com.mongodb.DBPort._open(DBPort.java:214)
oss-app_1    | 	at com.mongodb.DBPort.go(DBPort.java:107)
oss-app_1    | 	at com.mongodb.DBPort.call(DBPort.java:74)
oss-app_1    | 	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:283)
oss-app_1    | 	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:256)
oss-app_1    | 	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:289)
oss-app_1    | 	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:274)
oss-app_1    | 	at com.mongodb.DBCollection.findOne(DBCollection.java:710)
oss-app_1    | 	at com.mongodb.DBCollection.findOne(DBCollection.java:652)
oss-app_1    | 	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:343)
oss-app_1    | 	at com.mongodb.DBCollection.createIndex(DBCollection.java:467)
oss-app_1    | 	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:543)
oss-app_1    | 	at com.googlecode.pongo.runtime.PongoCollection.createIndex(PongoCollection.java:27)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.trans.model.MeasurementCollection.<init>(MeasurementCollection.java:24)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.trans.model.RascalMetrics.setDb(RascalMetrics.java:39)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.trans.model.RascalMetrics.<init>(RascalMetrics.java:22)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.getMetricResult(RascalMetricProvider.java:375)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.compute(RascalMetricProvider.java:279)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:207)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:1)
oss-app_1    | 	at org.eclipse.scava.platform.osgi.executors.MetricListExecutor.run(MetricListExecutor.java:140)
oss-app_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
oss-app_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
oss-app_1    | 	at java.lang.Thread.run(Thread.java:748)
oss-app_1    | 
oss-app_1    | ERROR [MetricListExecutor (DummyIFC, 20150422)] (11:53:07): Exception thrown during metric provider execution (MPC_Java_Q).
oss-app_1    | com.mongodb.MongoException$Network: can't call something : /127.0.0.1:27017/DummyIFC
oss-app_1    | 	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:292)
oss-app_1    | 	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:256)
oss-app_1    | 	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:289)
oss-app_1    | 	at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:274)
oss-app_1    | 	at com.mongodb.DBCollection.findOne(DBCollection.java:710)
oss-app_1    | 	at com.mongodb.DBCollection.findOne(DBCollection.java:652)
oss-app_1    | 	at com.mongodb.DBApiLayer$MyCollection.createIndex(DBApiLayer.java:343)
oss-app_1    | 	at com.mongodb.DBCollection.createIndex(DBCollection.java:467)
oss-app_1    | 	at com.mongodb.DBCollection.ensureIndex(DBCollection.java:543)
oss-app_1    | 	at com.googlecode.pongo.runtime.PongoCollection.createIndex(PongoCollection.java:27)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.trans.model.MeasurementCollection.<init>(MeasurementCollection.java:24)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.trans.model.RascalMetrics.setDb(RascalMetrics.java:39)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.trans.model.RascalMetrics.<init>(RascalMetrics.java:22)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.getMetricResult(RascalMetricProvider.java:375)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.compute(RascalMetricProvider.java:279)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:207)
oss-app_1    | 	at org.eclipse.scava.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:1)
oss-app_1    | 	at org.eclipse.scava.platform.osgi.executors.MetricListExecutor.run(MetricListExecutor.java:140)
oss-app_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
oss-app_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
oss-app_1    | 	at java.lang.Thread.run(Thread.java:748)
oss-app_1    | Caused by: java.io.IOException: couldn't connect to [/127.0.0.1:27017] bc:java.net.ConnectException: Connection refused (Connection refused)
oss-app_1    | 	at com.mongodb.DBPort._open(DBPort.java:214)
oss-app_1    | 	at com.mongodb.DBPort.go(DBPort.java:107)
oss-app_1    | 	at com.mongodb.DBPort.call(DBPort.java:74)
oss-app_1    | 	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:283)
oss-app_1    | 	... 20 more
```

**Comment by MarcioMateus** [comment]
Solved in commit 3055c583657533322b6d32cfcedba2edcf05eeaf
