### ISSUE TITLE
project/create form issue with field validation and/or submit

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava#56]
When you fill this form, if you don't do it exactly as it's expected to, like leaving any field empty and hit "Save", the button turns grey out and nothing happen.

When I take a look at the logs, I see errors like:

```
oss-app_1_a7edab0a86f8 | Nov 20, 2018 2:54:44 PM org.restlet.resource.ServerResource doCatch
oss-app_1_a7edab0a86f8 | WARNING: Exception or error caught in server resource
oss-app_1_a7edab0a86f8 | Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
(stack trace)
oss-app_1_a7edab0a86f8 |        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
oss-app_1_a7edab0a86f8 |        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
oss-app_1_a7edab0a86f8 |        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
oss-app_1_a7edab0a86f8 |        at java.lang.reflect.Method.invoke(Method.java:498)
oss-app_1_a7edab0a86f8 |        at org.restlet.resource.ServerResource.doHandle(ServerResource.java:521)
oss-app_1_a7edab0a86f8 |        ... 47 more
oss-app_1_a7edab0a86f8 |
oss-app_1_a7edab0a86f8 | Nov 20, 2018 2:54:44 PM org.restlet.engine.log.LogFilter afterHandle
oss-app_1_a7edab0a86f8 | INFO: 2018-11-20       14:54:44        172.19.0.11     -       172.19.0.7      8182    POST    /projects/create      -       500     486     94      12      http://oss-app:8182     Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0  http://wacke.ow2.org/project/create

```

**Comment by ambpro** [comment]
Please provide a reproduction scenario in order to investigate the issue!

**Comment by mhow2** [comment]
@ambpro : it's not as it wasn't easy to reproduce : " leaving any field empty and hit "Save", the button turns grey out and nothing happen."

**Comment by mhow2** [comment]
Here is [a video](https://nextcloud.ow2.org/index.php/s/sxeK2sbP5RbbrBf) that demonstrate the behavior I am observing. (The video might not play in the embeded player and have to download the file locally.)

**Comment by ambpro** [comment]
Okey @mhow2, I will investigate the problem :)
